title: "Netzwerk Kultur Kitzingen"
plugins:
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
logo: /helpics/IMG_4916.jpeg
favicon: true
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/NetzwerkKultur
  - name: E-Mail
    icon: âœ‰ï¸
    link: mailto:NetzwerkKultur@NoART.photography
  - name: Mastodon
    icon: ğŸ˜
    link: https://mastodon.social/@NetzwerkKultur
  - name: Impressum
    icon: âš’ï¸
    link: impressum.md
